### ISSUE TITLE
Missing required config: `bucket`

### ISSUE THREAD

**Issue by evoactivity** [he9qi/ember-cli-deploy-fastboot-s3#1]
Trying to run `ember deploy {{env}}` and it complains about this.

```bash
- Missing required config: `bucket`
Error: Missing required config: `bucket`
Error: Missing required config: `bucket`
    at Class.ensureConfigPropertySet (/Users/lpotter/Development/Apps/mashbo/node_modules/ember-cli-deploy-plugin/index.js:57:13)
    at Array.forEach (native)
    at Class.configure (/Users/lpotter/Development/Apps/mashbo/node_modules/ember-cli-deploy-plugin/index.js:39:19)
    at Object.fn (/Users/lpotter/Development/Apps/mashbo/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/lpotter/Development/Apps/mashbo/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
    at tryCatch (/Users/lpotter/Development/Apps/mashbo/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/lpotter/Development/Apps/mashbo/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/lpotter/Development/Apps/mashbo/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/lpotter/Development/Apps/mashbo/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Pipeline aborted
```

**Comment by sarjanen** [comment]
You need to set bucket and region in `fastboot-s3` and not in the `s3` like the readme says.

**Comment by willviles** [comment]
@Padchi - saved me some time there. Cheers!

**Comment by he9qi** [comment]
b37748792219a41695d8bafb0a5d8df17736dcf9
